name: Test on Multiple OS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Test on multiple OS
        node-version: [18, 20, 22]                      # Test on multiple Node.js versions
        attempt: [1, 2, 3, 4, 5]                        # Retry tests 5 times

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache npm dependencies to speed up builds

      - name: Fix OpenSSL issue on Node.js 18+
        run: |
          echo "Setting OpenSSL legacy provider for Node.js 18+"
          echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install dependencies (with retry)
        run: |
          echo "Attempting npm install..."
          for i in {1..3}; do
            npm install && break
            echo "npm install failed, retrying ($i/3)..."
            sleep 5
          done
        shell: bash

      - name: Install Karma
        run: |
          npm install -g karma
          npm install webpack webpack-cli --save-dev

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          npm test
